-- ============================================================================
-- CivicFix – Full Database Schema
-- Run this file in the Supabase SQL Editor (or via psql) to bootstrap all
-- tables, indexes, enums, and RLS policies.
-- ============================================================================

-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- 1. CUSTOM ENUM TYPES
-- ============================================================================
CREATE TYPE user_role           AS ENUM ('CITIZEN', 'OPERATOR', 'FIELD_TEAM', 'ADMIN');
CREATE TYPE complaint_status    AS ENUM ('SUBMITTED', 'ANALYZED', 'CLUSTERED', 'PLANNED',
                                        'IN_PROGRESS', 'RESOLVED', 'VERIFICATION_FAILED',
                                        'ESCALATED');
CREATE TYPE plan_status         AS ENUM ('PENDING_APPROVAL', 'APPROVED', 'REJECTED',
                                        'EXECUTING', 'COMPLETED');
CREATE TYPE task_status         AS ENUM ('PENDING', 'IN_PROGRESS', 'COMPLETED');

-- ============================================================================
-- 2. TABLES
-- ============================================================================

-- 2.1  users
-- ---------------------------------------------------------------------------
CREATE TABLE users (
  id             UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  email          TEXT        NOT NULL UNIQUE,
  password_hash  TEXT        NOT NULL,
  role           user_role   NOT NULL DEFAULT 'CITIZEN',
  name           TEXT        NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE users IS 'Registered CivicFix users – citizens, operators, field teams, admins.';

-- 2.2  complaints
-- ---------------------------------------------------------------------------
CREATE TABLE complaints (
  id             UUID              PRIMARY KEY DEFAULT uuid_generate_v4(),
  citizen_id     UUID              NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title          TEXT              NOT NULL,
  description    TEXT              NOT NULL,
  category       TEXT,
  priority       TEXT              DEFAULT 'MEDIUM',
  status         complaint_status  NOT NULL DEFAULT 'SUBMITTED',
  location_text  TEXT,
  latitude       DOUBLE PRECISION,
  longitude      DOUBLE PRECISION,
  photo_url      TEXT,
  created_at     TIMESTAMPTZ       NOT NULL DEFAULT now()
);

COMMENT ON TABLE complaints IS 'Civic complaints filed by citizens.';

-- 2.3  clusters
-- ---------------------------------------------------------------------------
CREATE TABLE clusters (
  id               UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  root_cause_title TEXT        NOT NULL,
  category         TEXT,
  summary          TEXT,
  complaint_count  INTEGER     NOT NULL DEFAULT 0,
  location_summary TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE clusters IS 'Groups of related / co-located complaints identified by the Cluster Agent.';

-- 2.4  complaint_clusters  (join table)
-- ---------------------------------------------------------------------------
CREATE TABLE complaint_clusters (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  complaint_id  UUID NOT NULL REFERENCES complaints(id) ON DELETE CASCADE,
  cluster_id    UUID NOT NULL REFERENCES clusters(id)   ON DELETE CASCADE,
  UNIQUE (complaint_id, cluster_id)
);

COMMENT ON TABLE complaint_clusters IS 'Many-to-many link between complaints and clusters.';

-- 2.5  plans
-- ---------------------------------------------------------------------------
CREATE TABLE plans (
  id              UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  complaint_id    UUID          REFERENCES complaints(id) ON DELETE SET NULL,
  cluster_id      UUID          REFERENCES clusters(id)   ON DELETE SET NULL,
  plan_title      TEXT          NOT NULL,
  estimated_cost  NUMERIC(12,2),
  estimated_hours NUMERIC(8,2),
  status          plan_status   NOT NULL DEFAULT 'PENDING_APPROVAL',
  created_at      TIMESTAMPTZ   NOT NULL DEFAULT now()
);

COMMENT ON TABLE plans IS 'Resolution plans generated by the Planning Agent.';

-- 2.6  tasks
-- ---------------------------------------------------------------------------
CREATE TABLE tasks (
  id             UUID         PRIMARY KEY DEFAULT uuid_generate_v4(),
  plan_id        UUID         NOT NULL REFERENCES plans(id) ON DELETE CASCADE,
  step_number    INTEGER      NOT NULL,
  task_name      TEXT         NOT NULL,
  description    TEXT,
  assigned_team  TEXT,
  status         task_status  NOT NULL DEFAULT 'PENDING',
  due_at         TIMESTAMPTZ
);

COMMENT ON TABLE tasks IS 'Individual action items within a plan, assigned to field teams.';

-- 2.7  verifications
-- ---------------------------------------------------------------------------
CREATE TABLE verifications (
  id               UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  complaint_id     UUID        NOT NULL REFERENCES complaints(id) ON DELETE CASCADE,
  is_resolved      BOOLEAN     NOT NULL DEFAULT false,
  citizen_feedback TEXT,
  photo_url        TEXT,
  verified_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE verifications IS 'Post-resolution verification records from the Verification Agent.';

-- 2.8  agent_audit_logs
-- ---------------------------------------------------------------------------
CREATE TABLE agent_audit_logs (
  id              UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
  complaint_id    UUID        REFERENCES complaints(id) ON DELETE SET NULL,
  agent_name      TEXT        NOT NULL,
  input_payload   JSONB,
  output_payload  JSONB,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE agent_audit_logs IS 'Immutable log of every autonomous agent invocation for traceability.';

-- ============================================================================
-- 3. INDEXES  (performance on common queries)
-- ============================================================================
CREATE INDEX idx_complaints_citizen       ON complaints(citizen_id);
CREATE INDEX idx_complaints_status        ON complaints(status);
CREATE INDEX idx_complaints_category      ON complaints(category);
CREATE INDEX idx_complaints_created       ON complaints(created_at DESC);
CREATE INDEX idx_complaint_clusters_cid   ON complaint_clusters(complaint_id);
CREATE INDEX idx_complaint_clusters_clid  ON complaint_clusters(cluster_id);
CREATE INDEX idx_plans_complaint          ON plans(complaint_id);
CREATE INDEX idx_plans_cluster            ON plans(cluster_id);
CREATE INDEX idx_plans_status             ON plans(status);
CREATE INDEX idx_tasks_plan               ON tasks(plan_id);
CREATE INDEX idx_tasks_status             ON tasks(status);
CREATE INDEX idx_verifications_complaint  ON verifications(complaint_id);
CREATE INDEX idx_audit_complaint          ON agent_audit_logs(complaint_id);
CREATE INDEX idx_audit_agent              ON agent_audit_logs(agent_name);
CREATE INDEX idx_audit_created            ON agent_audit_logs(created_at DESC);

-- ============================================================================
-- 4. ROW-LEVEL SECURITY (RLS)  –  enable per table, add policies as needed
-- ============================================================================
ALTER TABLE users              ENABLE ROW LEVEL SECURITY;
ALTER TABLE complaints         ENABLE ROW LEVEL SECURITY;
ALTER TABLE clusters           ENABLE ROW LEVEL SECURITY;
ALTER TABLE complaint_clusters ENABLE ROW LEVEL SECURITY;
ALTER TABLE plans              ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks              ENABLE ROW LEVEL SECURITY;
ALTER TABLE verifications      ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_audit_logs   ENABLE ROW LEVEL SECURITY;

-- Allow the service-role key (used by backend) full access on all tables
CREATE POLICY service_role_all ON users              FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY service_role_all ON complaints         FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY service_role_all ON clusters           FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY service_role_all ON complaint_clusters FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY service_role_all ON plans              FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY service_role_all ON tasks              FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY service_role_all ON verifications      FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY service_role_all ON agent_audit_logs   FOR ALL USING (true) WITH CHECK (true);

-- ============================================================================
-- Done.  All tables, indexes, enums, and baseline RLS policies are in place.
-- ============================================================================
