import { SchemaType, getGeminiModel } from '../config/gemini.js';
import { supabaseAdmin, dbQuery } from '../config/supabase.js';

// ---------------------------------------------------------------------------
// Agent identity
// ---------------------------------------------------------------------------
const AGENT_NAME = 'PlanningAgent';

// ---------------------------------------------------------------------------
// Business rules (mirror what the schema/UI will also enforce)
// ---------------------------------------------------------------------------
const HIGH_COST_THRESHOLD_INR = 10_000;
const APPROVAL_REQUIRED_PRIORITIES = new Set(['CRITICAL', 'HIGH']);

// ---------------------------------------------------------------------------
// Structured-output response schema
// ---------------------------------------------------------------------------
const taskItemSchema = {
  type: SchemaType.OBJECT,
  description: 'A single ordered work step for the field crew',
  properties: {
    stepNumber: {
      type: SchemaType.INTEGER,
      description: 'Sequential step number starting from 1'
    },
    taskName: {
      type: SchemaType.STRING,
      description: 'Short action-oriented name for this work step (max 80 chars)'
    },
    description: {
      type: SchemaType.STRING,
      description: 'Detailed instructions for the field crew member executing this step'
    },
    estimatedDurationMins: {
      type: SchemaType.INTEGER,
      description: 'Estimated time to complete this step in minutes'
    }
  },
  required: ['stepNumber', 'taskName', 'description', 'estimatedDurationMins']
};

const planningResponseSchema = {
  type: SchemaType.OBJECT,
  description: 'Operational work plan generated by the Planning Agent for a civic complaint',
  properties: {
    planTitle: {
      type: SchemaType.STRING,
      description: 'Concise title for the plan, suitable as a dashboard heading (max 120 chars)'
    },
    estimatedCostINR: {
      type: SchemaType.NUMBER,
      description: 'Total estimated cost of the repair in Indian Rupees (INR), as a numeric value'
    },
    estimatedHoursToFix: {
      type: SchemaType.NUMBER,
      description: 'Total estimated wall-clock hours from crew dispatch to completion'
    },
    requiredTeamType: {
      type: SchemaType.STRING,
      description:
        'Type of field crew required, e.g. "Road Maintenance Crew", "Sanitation Team", "Electrician Unit", "Plumbing & Sewerage Unit"'
    },
    operatorApprovalRequired: {
      type: SchemaType.BOOLEAN,
      description:
        'Whether this plan needs human operator approval before execution. Set true for CRITICAL/HIGH priority or cost > ₹10,000'
    },
    tasks: {
      type: SchemaType.ARRAY,
      description: 'Ordered list of actionable work steps for the field crew',
      items: taskItemSchema
    }
  },
  required: [
    'planTitle',
    'estimatedCostINR',
    'estimatedHoursToFix',
    'requiredTeamType',
    'operatorApprovalRequired',
    'tasks'
  ]
};

// ---------------------------------------------------------------------------
// System instruction
// ---------------------------------------------------------------------------
const SYSTEM_INSTRUCTION = `You are the Planning Agent for CivicFix, an Autonomous Civic Operations platform used by Indian municipalities.

Your role is to generate precise, actionable work-order plans for field crews who will resolve civic infrastructure issues.

Guidelines:
1. Break the resolution into a clear, ordered sequence of concrete tasks (minimum 3, maximum 8 steps).
2. Each task must be specific enough for a field worker to execute without further guidance.
3. Estimate costs realistically for Indian municipal contracts (materials + labour in INR).
4. Estimate total hours realistically — include mobilisation, execution, and site clean-up.
5. Assign the most appropriate crew type based on the complaint category.
6. Set operatorApprovalRequired to true if:
   - Priority is CRITICAL or HIGH, OR
   - Estimated cost exceeds ₹10,000
7. If cluster context is provided, factor in the scale of the problem (multiple complaints = larger crew, higher cost).
8. Use professional, technical language appropriate for municipal work orders.
9. Do not invent locations or details not present in the input data.`;

// ---------------------------------------------------------------------------
// Main agent function
// ---------------------------------------------------------------------------

/**
 * Runs the Planning Agent to generate an operational work-order plan.
 *
 * @param {Object} complaintData   – The complaint to plan for.
 *   @param {string}  complaintData.id
 *   @param {string}  complaintData.title
 *   @param {string}  complaintData.description
 *   @param {string}  complaintData.category
 *   @param {string}  complaintData.priority        – LOW | MEDIUM | HIGH | CRITICAL
 *   @param {number}  [complaintData.severityScore]
 *   @param {string}  [complaintData.location_text]
 *   @param {number}  [complaintData.latitude]
 *   @param {number}  [complaintData.longitude]
 *
 * @param {Object|null} clusterContext – Optional cluster this complaint belongs to.
 *   @param {string}  clusterContext.id
 *   @param {string}  clusterContext.root_cause_title
 *   @param {string}  [clusterContext.summary]
 *   @param {number}  [clusterContext.complaint_count]
 *   @param {string}  [clusterContext.location_summary]
 *
 * @returns {Promise<{
 *   plan: Object,         // full plan record saved to Supabase (includes generated id)
 *   tasks: Object[],      // task records saved to Supabase (each includes plan_id)
 *   geminiOutput: Object  // raw structured output from Gemini
 * }>}
 */
export async function runPlanningAgent(complaintData, clusterContext = null) {
  // ---- 1. Build model with structured output ----
  const model = getGeminiModel({
    systemInstruction: SYSTEM_INSTRUCTION,
    generationConfig: {
      responseMimeType: 'application/json',
      responseSchema: planningResponseSchema,
      temperature: 0.3  // slight creativity for varied task descriptions, still deterministic
    }
  });

  // ---- 2. Compose the user prompt ----
  const userPrompt = `
## Complaint Details
${JSON.stringify(complaintData, null, 2)}

${
  clusterContext
    ? `## Cluster Context (this complaint is part of a larger incident cluster)
${JSON.stringify(clusterContext, null, 2)}`
    : '## Cluster Context\nNone — this is a standalone complaint.'
}

Generate a complete operational work-order plan for the field crew to resolve this civic issue.
`.trim();

  // ---- 3. Build input payload for audit ----
  const inputPayload = {
    complaintId: complaintData.id,
    complaintTitle: complaintData.title,
    category: complaintData.category,
    priority: complaintData.priority,
    hasClusterContext: !!clusterContext,
    clusterId: clusterContext?.id ?? null
  };

  let geminiOutput;

  // ---- 4. Call Gemini ----
  try {
    const result = await model.generateContent({
      contents: [{ role: 'user', parts: [{ text: userPrompt }] }]
    });

    const responseText = result.response.text();
    geminiOutput = JSON.parse(responseText);

    // --- Normalise & enforce business rules ---

    // Ensure estimatedCostINR is non-negative
    geminiOutput.estimatedCostINR = Math.max(0, geminiOutput.estimatedCostINR);
    geminiOutput.estimatedHoursToFix = Math.max(0.25, geminiOutput.estimatedHoursToFix);

    // Override operatorApprovalRequired based on hard business rules
    // (Gemini output is advisory; server-side logic is authoritative)
    const costExceedsThreshold = geminiOutput.estimatedCostINR > HIGH_COST_THRESHOLD_INR;
    const priorityRequiresApproval = APPROVAL_REQUIRED_PRIORITIES.has(
      complaintData.priority?.toUpperCase()
    );
    geminiOutput.operatorApprovalRequired = costExceedsThreshold || priorityRequiresApproval;

    // Ensure tasks are sorted by stepNumber and steps are 1-indexed
    geminiOutput.tasks = (geminiOutput.tasks || [])
      .sort((a, b) => a.stepNumber - b.stepNumber)
      .map((task, idx) => ({
        ...task,
        stepNumber: idx + 1,
        estimatedDurationMins: Math.max(1, task.estimatedDurationMins)
      }));
  } catch (error) {
    console.error(`[${AGENT_NAME}] Gemini call failed:`, error.message);

    await logToAudit(complaintData.id, inputPayload, {
      error: error.message,
      status: 'FAILED'
    });

    throw error;
  }

  // ---- 5. Persist plan to Supabase ----
  let savedPlan;
  let savedTasks = [];

  try {
    // 5a. Insert into plans table
    const planStatus = geminiOutput.operatorApprovalRequired
      ? 'PENDING_APPROVAL'
      : 'APPROVED';

    const [planRecord] = await dbQuery(
      supabaseAdmin
        .from('plans')
        .insert({
          complaint_id: complaintData.id || null,
          cluster_id: clusterContext?.id || null,
          plan_title: geminiOutput.planTitle,
          estimated_cost: geminiOutput.estimatedCostINR,
          estimated_hours: geminiOutput.estimatedHoursToFix,
          status: planStatus
        })
        .select()
    );

    savedPlan = planRecord;

    // 5b. Insert all tasks linked to this plan
    const taskRows = geminiOutput.tasks.map((task) => ({
      plan_id: savedPlan.id,
      step_number: task.stepNumber,
      task_name: task.taskName,
      description: task.description,
      assigned_team: geminiOutput.requiredTeamType,
      status: 'PENDING'
      // due_at is left null — to be set by operator during approval
    }));

    savedTasks = await dbQuery(
      supabaseAdmin.from('tasks').insert(taskRows).select()
    );
  } catch (dbError) {
    console.error(`[${AGENT_NAME}] Supabase write failed:`, dbError.message);

    await logToAudit(complaintData.id, inputPayload, {
      geminiOutput,
      dbError: dbError.message,
      status: 'DB_WRITE_FAILED'
    });

    throw dbError;
  }

  // ---- 6. Persist audit log ----
  await logToAudit(complaintData.id, inputPayload, {
    planId: savedPlan.id,
    taskCount: savedTasks.length,
    planStatus: savedPlan.status,
    estimatedCostINR: geminiOutput.estimatedCostINR,
    estimatedHoursToFix: geminiOutput.estimatedHoursToFix,
    operatorApprovalRequired: geminiOutput.operatorApprovalRequired
  });

  return {
    plan: savedPlan,
    tasks: savedTasks,
    geminiOutput
  };
}

// ---------------------------------------------------------------------------
// Audit logger — non-fatal
// ---------------------------------------------------------------------------
async function logToAudit(complaintId, inputPayload, outputPayload) {
  try {
    await dbQuery(
      supabaseAdmin.from('agent_audit_logs').insert({
        complaint_id: complaintId || null,
        agent_name: AGENT_NAME,
        input_payload: inputPayload,
        output_payload: outputPayload
      })
    );
  } catch (err) {
    console.warn(`[${AGENT_NAME}] Audit log write failed:`, err.message);
  }
}

export default { runPlanningAgent };
